### ISSUE TITLE
Equinix Metal ARM64 Cluster will expire soon

### ISSUE THREAD

**Issue by hmsjy2017** [ryanfortner/ryanfortner#4]
ARM's ManiSha Nigam told me that the 3 -month period for server availability will expire on July 25. He needs to know if the server is still in use or whether it can be released. He sent you an email but you may not see it.

**Comment by ryanfortner** [comment]
I have seen and responded to the email. I don’t believe we have much of a need for the server, so passing it on to another project is probably the best decision.
